// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://jtrorcbkufgdblethefh.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cm9yY2JrdWZnZGJsZXRoZWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI1MzU5NDksImV4cCI6MjA0ODExMTk0OX0.Ec76dgUQMrrbwm3MizsNuE06C-TMyNYiXZvxFsGTFJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);